name: raff
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: 3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sizer: 2.0.15
  convert: 3.1.1
  scoped_model: 2.0.0
  flutter_secure_storage: 8.1.0
  url_launcher: 6.1.11
  shared_preferences: 2.2.2
  flutter_spinkit: 5.2.0
  permission_handler: 11.0.1
  smooth_page_indicator: 1.1.0
  flutter_svg: 1.1.6
  awesome_dialog: 3.2.1
  connectivity_plus: 6.1.3
  intl: 0.19.0
  geolocator: 11.0.0
  oktoast: 3.4.0
  adaptive_action_sheet: 2.0.2
  image_picker: 1.0.4
  get: 4.6.6
  google_fonts: 6.0.0
  otp_text_field: 1.1.3
  either_dart:
  lottie: 2.3.2
  encrypt: 5.0.1
  geocoding: 3.0.0
  keyboard_actions: 4.2.0
  animations: 2.0.1
  video_player: 2.9.1
  flutter_launcher_icons: 0.13.1
  camera: 0.10.2+1
  scrollable_positioned_list: 0.3.8
  diacritic: 0.1.6
  intl_utils: 2.8.7
  package_info_plus: 8.3.0
flutter_launcher_icons:
  image_path_ios: "assets/app_icon.png"
  android: false
  ios: true
  remove_alpha_ios: true
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/categories/

flutter_intl:
  enabled: true
  use_deferred_loading: true
